services:
  # The Database
  postgres:
    image: postgres:15-alpine
    container_name: hrms_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: hrms_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Database GUI (Optional, but useful for inspection)
  pgadmin:
    image: dpage/pgadmin4
    container_name: hrms_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hrms.internal
      PGADMIN_DEFAULT_PASSWORD: secretpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: